# Generated by Django 5.0.4 on 2024-04-21 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pmta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.CharField(max_length=20)),
                ('number_send', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=20)),
                ('id_mint', models.CharField(max_length=20)),
                ('set_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Raports.set')),
            ],
        ),
        migrations.CreateModel(
            name='Mint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mint', models.CharField(max_length=20)),
                ('open_rate', models.CharField(max_length=20)),
                ('nr_clicks', models.CharField(max_length=20)),
                ('nr_unsub', models.CharField(max_length=20)),
                ('abuse', models.CharField(max_length=20)),
                ('set_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Raports.set')),
            ],
        ),
    ]
